

USE q1u9gnricx1xg22v;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Forums;
DROP TABLE IF EXISTS GameTags;
DROP TABLE IF EXISTS Games;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS Threads;
DROP TABLE IF EXISTS UserGames;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Votes;
DROP TABLE IF EXISTS UserFriends;

SET FOREIGN_KEY_CHECKS = 1;